### ISSUE TITLE
"kustomize - Generate deployment manifest" task fails in orders containing SAS Workload Management

### ISSUE THREAD

**Issue by hyweldaniels** [sassoftware/viya4-deployment#121]
When an order contains SAS Workload Management, the playbook fails when generating the deployment manifest.

The issue occurs because sas-storageclass.yaml (https://github.com/sassoftware/viya4-deployment/blob/7e89b16edc7369683422b1950dd57a261be320b3/roles/vdm/templates/transformers/sas-storageclass.yaml) attempts to add a Storage Class name to the volumeClaimTemplate for every Stateful Set.

However the sas-workload-orchestrator Stateful Set that comes with SAS Workload Management does not contain a volumeClaimTemplate attribute, leading to a build error;
```
Error: failed to apply json patch '- op: add
  path: /spec/volumeClaimTemplates/0/spec/storageClassName
  value: sas': add operation does not apply: doc is missing path: "/spec/volumeClaimTemplates/0/spec/storageClassName": missing value
```
A possible workaround, that I have tested, would be to explicitly exclude sas-workload-orchestrator using an annotation selector;

```yaml
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: sas-ss-storageclass
patch: |-
  - op: add
    path: /spec/volumeClaimTemplates/0/spec/storageClassName
    value: sas
target:
  group: apps
  kind: StatefulSet
  annotationSelector: sas.com/component-name != sas-workload-orchestrator
```
